# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zync_example/Zync_example.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example || ORIG_REF_NAME==Zync_example} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_processing_system7_0_0/Zync_example_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_processing_system7_0_0 || ORIG_REF_NAME==Zync_example_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_proc_sys_reset_0_0/Zync_example_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_proc_sys_reset_0_0 || ORIG_REF_NAME==Zync_example_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_xbar_0/Zync_example_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_xbar_0 || ORIG_REF_NAME==Zync_example_xbar_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_axi_interconnect_0_0/Zync_example_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_axi_interconnect_0_0 || ORIG_REF_NAME==Zync_example_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_axi_gpio_0_0/Zync_example_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_axi_gpio_0_0 || ORIG_REF_NAME==Zync_example_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_axi_bram_ctrl_0_0/Zync_example_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Zync_example_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_blk_mem_gen_0_0/Zync_example_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_blk_mem_gen_0_0 || ORIG_REF_NAME==Zync_example_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_auto_pc_1/Zync_example_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_auto_pc_1 || ORIG_REF_NAME==Zync_example_auto_pc_1} -quiet] -quiet

# IP: bd/Zync_example/ip/Zync_example_auto_pc_0/Zync_example_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zync_example_auto_pc_0 || ORIG_REF_NAME==Zync_example_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Asus/OneDrive/Documents/AMD Vivado Vitis Projects/project_1/project_1.gen/sources_1/bd/Zync_example/Zync_example_ooc.xdc
