# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Asus/OneDrive/Documents/AMD Vivado Vitis Projects/project_1/project_1.srcs/sources_1/bd/Zync_example/ip/Zync_example_blk_mem_gen_0_0/Zync_example_blk_mem_gen_0_0.xci
# IP: The module: 'Zync_example_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/OneDrive/Documents/AMD Vivado Vitis Projects/project_1/project_1.gen/sources_1/bd/Zync_example/ip/Zync_example_blk_mem_gen_0_0/Zync_example_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_example_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Asus/OneDrive/Documents/AMD Vivado Vitis Projects/project_1/project_1.srcs/sources_1/bd/Zync_example/ip/Zync_example_blk_mem_gen_0_0/Zync_example_blk_mem_gen_0_0.xci
# IP: The module: 'Zync_example_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/OneDrive/Documents/AMD Vivado Vitis Projects/project_1/project_1.gen/sources_1/bd/Zync_example/ip/Zync_example_blk_mem_gen_0_0/Zync_example_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_example_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
